import { Container } from "../Container/Container.styled";
import {
  AboutImg,
  AboutLinespan,
  AboutMainWrapper,
  AboutSubtitle,
  AboutSvg,
  AboutSvgLine,
  AboutText,
  AboutTitle,
  AboutTitleSpan,
  AboutWarapperSvgText,
  AboutWrapperLine,
  MarqueeText,
  MarqueeWrapper,
} from "./About.styled";

import Icons from "../../img/svg/icons.svg";

export const About = () => {
  return (
    <>
      <Container>
        <AboutMainWrapper>
          <AboutTitle id="about">
            a Story that started with
            <AboutTitleSpan>
              {" "}
              one simple <br className="about-title-mobile" /> ape
            </AboutTitleSpan>
          </AboutTitle>
          <AboutSubtitle>
            WHO GOT <br className="about-subtitle-mobile" /> FED UP WITH BORING
            AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF ESCAPING AND
            DYNAMIC JOURNEY ON THE <br className="about-subtitle-tablet" />
            YACHT
          </AboutSubtitle>
          <AboutWarapperSvgText>
            <AboutSvg>
              <use href={`${Icons}#icon-cross`} />
            </AboutSvg>
            <AboutText>
              EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
              ARE RANDOMLY GENERATED BY USERS
            </AboutText>
          </AboutWarapperSvgText>
          <AboutImg />
        </AboutMainWrapper>
      </Container>
      <AboutWrapperLine>
        <MarqueeWrapper>
          <MarqueeText>
            <AboutLinespan>
              Destroy stereotypes
              <AboutSvgLine>
                <use href={`${Icons}#icon-cross`} />
              </AboutSvgLine>
            </AboutLinespan>
            <AboutLinespan>
              Have no limits
              <AboutSvgLine>
                <use href={`${Icons}#icon-cross`} />
              </AboutSvgLine>
            </AboutLinespan>
            <AboutLinespan>Break rulles</AboutLinespan>
          </MarqueeText>
        </MarqueeWrapper>
      </AboutWrapperLine>
    </>
  );
};
